### ISSUE TITLE
 what library java inherit the "com.validation.AppValidator" class?

### ISSUE THREAD

**Issue by p4535992** [holmes1491/s-crud-devtool#1]
Hi sorry to bother can yuo tell me what library java inherit the "com.validation.AppValidator" class?
Ty  in advance.

**Comment by holmes1491** [comment]
dude this is custom made a class for a web-app lock with a "network adapter"
sorry, this jar is not shareable but if you want to know which java library I used in this class is then refer  "com.webapp.utils.NICAddress"

**Comment by p4535992** [comment]
ty for the clarification.
Greetings.
